/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    protocols: Protocol;
    medications: Medication;
    'hospital-networks': HospitalNetwork;
    'hospital-capabilities': HospitalCapability;
    hospitals: Hospital;
    'hospital-change-requests': HospitalChangeRequest;
    'base-change-requests': BaseChangeRequest;
    bases: Base;
    assets: Asset;
    calculators: Calculator;
    notifications: Notification;
    'audit-log': AuditLog;
    'notification-settings': NotificationSetting;
    'push-notifications': PushNotification;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    protocols: ProtocolsSelect<false> | ProtocolsSelect<true>;
    medications: MedicationsSelect<false> | MedicationsSelect<true>;
    'hospital-networks': HospitalNetworksSelect<false> | HospitalNetworksSelect<true>;
    'hospital-capabilities': HospitalCapabilitiesSelect<false> | HospitalCapabilitiesSelect<true>;
    hospitals: HospitalsSelect<false> | HospitalsSelect<true>;
    'hospital-change-requests': HospitalChangeRequestsSelect<false> | HospitalChangeRequestsSelect<true>;
    'base-change-requests': BaseChangeRequestsSelect<false> | BaseChangeRequestsSelect<true>;
    bases: BasesSelect<false> | BasesSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    calculators: CalculatorsSelect<false> | CalculatorsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'notification-settings': NotificationSettingsSelect<false> | NotificationSettingsSelect<true>;
    'push-notifications': PushNotificationsSelect<false> | PushNotificationsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Site pages (admin only)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Blog posts (admin only)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Media library (admin only)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Post categories (admin only)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User management - Admin can add/delete, Content team can edit details
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * User role determines access level
   */
  role: 'user' | 'content-team' | 'admin-team';
  /**
   * Content Team or Admin must approve new user signups
   */
  approved?: boolean | null;
  /**
   * User account status
   */
  status: 'pending' | 'active' | 'inactive';
  /**
   * Reason for rejecting this user registration (sent to user in notification email)
   */
  rejectionReason?: string | null;
  /**
   * Default protocol level for this user. Users can still toggle between levels, but this will be their starting preference.
   */
  defaultServiceLine?: ('BLS' | 'ALS' | 'CCT') | null;
  /**
   * Opt-in to receive push notifications for protocol updates and announcements
   */
  pushNotificationsEnabled?: boolean | null;
  /**
   * Opt-in to receive email notifications for account updates and requests
   */
  emailNotificationsEnabled?: boolean | null;
  /**
   * Device tokens for push notifications (automatically managed by mobile app)
   */
  fcmTokens?:
    | {
        token: string;
        platform?: ('android' | 'ios' | 'web') | null;
        lastUsed?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Choose which email notifications you want to receive
   */
  notificationPreferences?: {
    /**
     * Get notified when new users register (Admin/Content team only)
     */
    userRegistrations?: boolean | null;
    /**
     * Get notified when users submit change requests (Admin/Content team only)
     */
    changeRequests?: boolean | null;
    /**
     * Get notified about system events and critical updates (Admin team only)
     */
    systemNotifications?: boolean | null;
  };
  /**
   * Upload a profile picture
   */
  profileImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Clinical protocols with structured sections and action steps
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protocols".
 */
export interface Protocol {
  id: number;
  _order?: string | null;
  /**
   * Protocol code (e.g., SB204, T705, M301)
   */
  code: string;
  title: string;
  category:
    | 'medical'
    | 'trauma'
    | 'pediatric'
    | 'neonatal'
    | 'obgyn'
    | 'procedures'
    | 'behavioral'
    | 'environmental'
    | 'special-ops';
  subcategory?: string | null;
  /**
   * Year last modified (e.g., 2024)
   */
  lastModified?: string | null;
  /**
   * Sections are drag-and-drop sortable! Use the ⋮⋮ handle to reorder.
   */
  sections: {
    /**
     * e.g., "Inclusion Criteria", "Protocol", "Differential Diagnosis"
     */
    heading: string;
    /**
     * Who can view/perform this section. Leave empty for all certification levels.
     */
    scope?: ('BLS' | 'ALS' | 'CCT')[] | null;
    /**
     * Optional alert/note to show at top of section
     */
    note?: string | null;
    /**
     * How should this section be displayed?
     */
    contentType: 'actionSteps' | 'bulletList' | 'richText';
    /**
     * Use the editor to create formatted bullet lists
     */
    bulletList?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    actionSteps?:
      | {
          /**
           * Step number (can use decimals like 3.5 for inserted steps)
           */
          stepNumber: number;
          /**
           * Main action text
           */
          action: string;
          /**
           * Who can perform this step. Leave empty for all levels.
           */
          scope?: ('BLS' | 'ALS' | 'CCT')[] | null;
          /**
           * Timing indicator (e.g., "q3-5min", "continuous", "q2min")
           */
          timing?: string | null;
          /**
           * Check if this step requires medical control authorization
           */
          requiresMedControl?: boolean | null;
          /**
           * Other protocols referenced in this step (for navigation)
           */
          protocolReferences?:
            | {
                protocol: number | Protocol;
                /**
                 * Text to display (e.g., "T508", "VF/VT Protocol")
                 */
                label?: string | null;
                id?: string | null;
              }[]
            | null;
          /**
           * Sub-bullets or additional details
           */
          details?:
            | {
                detail: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Link medications used in this protocol
   */
  medications?: (number | Medication)[] | null;
  /**
   * Other protocols referenced in this one
   */
  relatedProtocols?: (number | Protocol)[] | null;
  /**
   * Comma-separated keywords for search
   */
  keywords: string;
  tags?: ('cardiac' | 'respiratory' | 'trauma' | 'neurological' | 'pediatric' | 'critical')[] | null;
  effectiveDate?: string | null;
  lastReviewed?: string | null;
  /**
   * Override which calculators are shown and their order for this protocol
   */
  calculatorOverrides?:
    | {
        calculator: number | Calculator;
        /**
         * Override the calculator's defaultOrder for this protocol
         */
        order?: number | null;
        /**
         * If true, hide this calculator for this protocol even if tags would otherwise match
         */
        hidden?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Diagrams, flowcharts, reference images, or PDFs
   */
  attachments?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Medication reference database with dosing and clinical information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medications".
 */
export interface Medication {
  id: number;
  name: string;
  /**
   * Generic name if different from brand name
   */
  genericName?: string | null;
  class:
    | 'vasopressor'
    | 'antiarrhythmic'
    | 'analgesic'
    | 'sedative'
    | 'antiemetic'
    | 'bronchodilator'
    | 'anticonvulsant'
    | 'antihypertensive'
    | 'antiplatelet'
    | 'anticoagulant'
    | 'paralytic'
    | 'reversal'
    | 'other';
  /**
   * Who can administer this medication
   */
  scope: ('BLS' | 'ALS' | 'CCT')[];
  /**
   * Add a row for each route (IV, IM, PO, etc.)
   */
  doses: {
    route: 'IV' | 'IO' | 'IV/IO' | 'IM' | 'SQ' | 'PO' | 'SL' | 'IN' | 'INH' | 'ET' | 'PR';
    adultDose: string;
    pediatricDose?: string | null;
    concentration?: string | null;
    interval?: string | null;
    maxDose?: string | null;
    rate?: string | null;
    id?: string | null;
  }[];
  /**
   * When to use this medication
   */
  indications: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * When NOT to use this medication
   */
  contraindications?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Special considerations or warnings
   */
  precautions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * How the medication works (optional, for education)
   */
  mechanismOfAction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  onset?: string | null;
  duration?: string | null;
  /**
   * Common and serious adverse effects
   */
  sideEffects?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * How to mix/prepare the medication
   */
  mixing?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What it can/cannot be mixed with
   */
  compatibility?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Titration guidelines (for infusions)
   */
  titration?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Any special administration instructions
   */
  specialInstructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pregnancyCategory?: ('A' | 'B' | 'C' | 'D' | 'X') | null;
  /**
   * Any additional notes or pearls
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Clinical calculators and quick tools metadata
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculators".
 */
export interface Calculator {
  id: number;
  title: string;
  /**
   * This must match a key in the front end calculator registry
   */
  key: string;
  /**
   * Brief description of what this calculator does
   */
  description?: string | null;
  /**
   * Primary category for organizing calculators
   */
  category: 'neuro' | 'respiratory' | 'cardiovascular' | 'medications' | 'pediatric' | 'trauma' | 'general';
  /**
   * Which service lines this calculator applies to
   */
  serviceLines?: ('BLS' | 'ALS' | 'MICU' | 'Flight' | 'CCT' | 'CommSpec')[] | null;
  /**
   * Tags for matching calculators to protocols (e.g., "RSI", "Vent", "Peds", "Weight based")
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Default ordering for quick tools (lower numbers appear first)
   */
  defaultOrder?: number | null;
  /**
   * Disable to hide calculator system-wide
   */
  enabled?: boolean | null;
  /**
   * Calculators can be hidden per protocol even if tags match
   */
  showByDefault?: boolean | null;
  /**
   * User who created this calculator
   */
  createdBy?: (number | null) | User;
  /**
   * User who last updated this calculator
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hospital systems and networks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-networks".
 */
export interface HospitalNetwork {
  id: number;
  name: string;
  /**
   * Default logo for hospitals in this network
   */
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Define capability types and their certification levels (e.g., Trauma with levels I-IV)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-capabilities".
 */
export interface HospitalCapability {
  id: number;
  /**
   * The name of this capability type
   */
  name: string;
  /**
   * Category for organizing and filtering capabilities
   */
  category: 'trauma' | 'cardiac' | 'neuro' | 'obstetrics' | 'other';
  /**
   * Define all possible certification levels for this capability. These levels will appear as options when assigning this capability to hospitals.
   */
  levels: {
    /**
     * Enter the level name exactly as it should appear (e.g., "Level I", "Level 2 - Moderate Risk")
     */
    level: string;
    /**
     * Provide a short summary of what this level includes so hospital cards and selectors can explain it.
     */
    description?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Hospital directory with contact info, capabilities, and EMS notes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospitals".
 */
export interface Hospital {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Parent network/system this hospital belongs to
   */
  network?: (number | null) | HospitalNetwork;
  /**
   * Override the network logo with a hospital-specific logo
   */
  networkLogoOverride?: (number | null) | Media;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  /**
   * Paste from Google Maps (e.g., "39.136774, -84.502021"). We'll parse it automatically.
   */
  coordinates?: string | null;
  /**
   * Auto-populated from coordinates field
   */
  latitude?: number | null;
  /**
   * Auto-populated from coordinates field
   */
  longitude?: number | null;
  /**
   * Primary EMS contact number
   */
  squadPhone?: string | null;
  /**
   * Secondary contacts such as charge nurses, security, etc.
   */
  otherPhones?:
    | {
        label?: string | null;
        phoneNumber?: string | null;
        /**
         * Short context for when to call this contact.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Entry codes for EMS access
   */
  doorCodes?:
    | {
        label?: string | null;
        code?: string | null;
        /**
         * Optional context such as time restrictions or access notes.
         */
        notes?: string | null;
        /**
         * Displayed in quick actions for rapid access.
         */
        isPrimary?: boolean | null;
        /**
         * Purely visual – helps differentiate door cards in the UI.
         */
        colorTheme?: ('sunset' | 'slate' | 'sky' | 'emerald' | 'violet' | 'rose') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Details for air medical operations.
   */
  helipad?: {
    identifier?: string | null;
    nightOperations?: boolean | null;
    preferredApproach?: string | null;
    notes?: string | null;
  };
  /**
   * Upload or link to common approach maps (ambulance route, bays, interior, etc.)
   */
  campusMaps?:
    | {
        label: string;
        /**
         * Optional stable ID used for deep-linking tabs. Defaults to a slugified label if blank.
         */
        slug?: string | null;
        mapType?: ('ambulance' | 'interior' | 'parking' | 'lz' | 'custom') | null;
        description?: string | null;
        mapMedia?: (number | null) | Media;
        /**
         * Optional link to open in Google Maps, PDF, etc.
         */
        externalUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add clinical capabilities and their certification levels
   */
  capabilities?:
    | {
        /**
         * Select a capability type (e.g., Trauma, PCI, Stroke)
         */
        capability: number | HospitalCapability;
        /**
         * Select the certification level from the dropdown. Options are loaded from the selected Capability Type.
         */
        level: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional information for EMS crews
   */
  notes?: string | null;
  /**
   * Callouts that should surface in the card UI.
   */
  hazards?:
    | {
        note: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown under the card (e.g., “Air Care & Mobile Care education team”).
   */
  sourceAttribution?: string | null;
  /**
   * User who created this record
   */
  createdBy?: (number | null) | User;
  /**
   * User who last updated this record
   */
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * User-submitted requests to add or update hospital information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-change-requests".
 */
export interface HospitalChangeRequest {
  id: number;
  /**
   * Type of change request
   */
  type: 'add' | 'update';
  /**
   * Hospital to update (required for update requests)
   */
  targetHospital?: (number | null) | Hospital;
  /**
   * The data to add or update
   */
  proposedData?: {
    name?: string | null;
    address?: {
      line1?: string | null;
      line2?: string | null;
      city?: string | null;
      state?: string | null;
      zip?: string | null;
    };
    coordinates?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    squadPhone?: string | null;
    otherPhones?:
      | {
          label?: string | null;
          phoneNumber?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    doorCodes?:
      | {
          label?: string | null;
          code?: string | null;
          notes?: string | null;
          isPrimary?: boolean | null;
          colorTheme?: ('sunset' | 'slate' | 'sky' | 'emerald' | 'violet' | 'rose') | null;
          id?: string | null;
        }[]
      | null;
    helipad?: {
      identifier?: string | null;
      nightOperations?: boolean | null;
      preferredApproach?: string | null;
      notes?: string | null;
    };
    campusMaps?:
      | {
          label: string;
          slug?: string | null;
          mapType?: string | null;
          description?: string | null;
          mapMedia?: (number | null) | Media;
          externalUrl?: string | null;
          id?: string | null;
        }[]
      | null;
    capabilities?:
      | {
          capability?: (number | null) | HospitalCapability;
          level?: string | null;
          id?: string | null;
        }[]
      | null;
    notes?: string | null;
    hazards?:
      | {
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    sourceAttribution?: string | null;
  };
  /**
   * User who submitted this request
   */
  submittedBy?: (number | null) | User;
  /**
   * When set to approved, changes are automatically applied to the hospital
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Internal notes about this request
   */
  adminNotes?: string | null;
  /**
   * Reason for rejecting this request (sent to user in notification email)
   */
  rejectionReason?: string | null;
  /**
   * When the change was automatically applied
   */
  appliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User-submitted requests to add or update base information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "base-change-requests".
 */
export interface BaseChangeRequest {
  id: number;
  /**
   * Type of change request
   */
  type: 'add' | 'update';
  /**
   * Base to update (required for update requests)
   */
  targetBase?: (number | null) | Base;
  /**
   * The data to add or update
   */
  proposedData?: {
    name?: string | null;
    address?: {
      line1?: string | null;
      line2?: string | null;
      city?: string | null;
      state?: string | null;
      zip?: string | null;
    };
    coordinates?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    squadPhone?: string | null;
    contactInfo?:
      | {
          label?: string | null;
          phoneNumber?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    doorCodes?:
      | {
          label?: string | null;
          code?: string | null;
          notes?: string | null;
          id?: string | null;
        }[]
      | null;
    hazards?:
      | {
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    notes?: string | null;
    sourceAttribution?: string | null;
  };
  /**
   * User who submitted this request
   */
  submittedBy?: (number | null) | User;
  /**
   * When set to approved, changes are automatically applied to the base
   */
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Internal notes about this request
   */
  adminNotes?: string | null;
  /**
   * Reason for rejecting this request (sent to user in notification email)
   */
  rejectionReason?: string | null;
  /**
   * When the change was automatically applied
   */
  appliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * EMS base locations and station information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bases".
 */
export interface Base {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name)
   */
  slug: string;
  /**
   * Parent network/system this base belongs to (e.g., UC Health)
   */
  network?: (number | null) | HospitalNetwork;
  /**
   * Override the network logo with a base-specific logo
   */
  networkLogoOverride?: (number | null) | Media;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
  };
  /**
   * Paste from Google Maps (e.g., "39.136774, -84.502021"). We'll parse it automatically.
   */
  coordinates?: string | null;
  /**
   * Auto-populated from coordinates field
   */
  latitude?: number | null;
  /**
   * Auto-populated from coordinates field
   */
  longitude?: number | null;
  /**
   * Primary squad/base contact number
   */
  squadPhone?: string | null;
  /**
   * Additional phone numbers and contact methods
   */
  contactInfo?:
    | {
        label?: string | null;
        phoneNumber?: string | null;
        /**
         * Short description of when to use this contact
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Entry codes for base access
   */
  doorCodes?:
    | {
        label?: string | null;
        code?: string | null;
        /**
         * Optional context such as time restrictions or access notes.
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select vehicles and units stationed at this base. Assets already assigned to other bases will not appear in the list.
   */
  assets?: (number | Asset)[] | null;
  /**
   * Important notes and hazards for EMS crews
   */
  hazards?:
    | {
        note: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional information about this base
   */
  notes?: string | null;
  /**
   * Shown at bottom of page (e.g., "Air Care & Mobile Care education team")
   */
  sourceAttribution?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * EMS vehicles and units (ambulances, helicopters, etc.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: number;
  /**
   * Unique identifier for this asset
   */
  name: string;
  /**
   * Type of vehicle or unit
   */
  type: 'bls' | 'als' | 'micu' | 'cct' | 'helicopter' | 'chase' | 'support' | 'other';
  /**
   * Emoji to display with this asset (e.g., 🚑, 🚁, 🚓)
   */
  emoji?: string | null;
  /**
   * Internal unit identifier
   */
  unitId?: string | null;
  /**
   * Vehicle license plate number
   */
  licensePlate?: string | null;
  /**
   * Aircraft tail number (helicopters only)
   */
  tailNumber?: string | null;
  /**
   * Detailed description of equipment and capabilities (shown in tooltip on hover)
   */
  capabilities?: string | null;
  /**
   * Additional internal notes about this asset
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Track all email notifications sent by the system
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  /**
   * Type of notification sent
   */
  type:
    | 'user_registers'
    | 'user_approved'
    | 'user_deactivated'
    | 'user_deleted'
    | 'base_change_request_submitted'
    | 'hospital_change_request_submitted'
    | 'new_base_submitted'
    | 'new_hospital_submitted'
    | 'request_approved'
    | 'request_denied'
    | 'user_registration_admin'
    | 'user_rejected'
    | 'hospital_request_submitted_admin'
    | 'hospital_request_approved'
    | 'hospital_request_rejected'
    | 'base_request_submitted_admin'
    | 'base_request_approved'
    | 'base_request_rejected';
  /**
   * Email address of the recipient
   */
  recipient: string;
  /**
   * User who received the notification (if applicable)
   */
  recipientUser?: (number | null) | User;
  /**
   * User who triggered/created this notification
   */
  createdBy?: (number | null) | User;
  /**
   * Email subject line
   */
  subject: string;
  /**
   * HTML content of the email (for reference)
   */
  htmlContent?: string | null;
  /**
   * Status of the notification
   */
  status: 'pending' | 'sent' | 'failed';
  /**
   * Email ID from the email service provider (e.g., Resend)
   */
  emailId?: string | null;
  /**
   * Error message if the email failed to send
   */
  error?: string | null;
  /**
   * User related to this notification (e.g., user who registered)
   */
  relatedUser?: (number | null) | User;
  /**
   * Hospital change request related to this notification
   */
  relatedHospitalRequest?: (number | null) | HospitalChangeRequest;
  /**
   * Base change request related to this notification
   */
  relatedBaseRequest?: (number | null) | BaseChangeRequest;
  /**
   * When the notification was successfully sent
   */
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Detailed audit trail of all changes made to change requests
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  /**
   * Type of action performed
   */
  action: 'created' | 'updated' | 'approved' | 'rejected' | 'amended' | 'status_changed';
  /**
   * Collection that was modified
   */
  collection: 'users' | 'hospital-change-requests' | 'base-change-requests' | 'hospitals' | 'bases';
  /**
   * ID of the document that was modified
   */
  documentId: string;
  /**
   * User who made the change
   */
  changedBy: number | User;
  /**
   * Detailed list of field changes
   */
  changes?:
    | {
        /**
         * Name of the field that changed
         */
        field: string;
        /**
         * Previous value (JSON stringified if complex)
         */
        previousValue?: string | null;
        /**
         * New value (JSON stringified if complex)
         */
        newValue?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional metadata about the change
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * IP address of the user who made the change
   */
  ipAddress?: string | null;
  /**
   * User agent of the browser/client
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings".
 */
export interface NotificationSetting {
  id: number;
  notificationType:
    | 'user_registers'
    | 'user_approved'
    | 'user_deactivated'
    | 'user_deleted'
    | 'base_change_request_submitted'
    | 'hospital_change_request_submitted'
    | 'new_base_submitted'
    | 'new_hospital_submitted'
    | 'request_approved'
    | 'request_denied';
  adminNotifications?: {
    pushEnabled?: boolean | null;
    emailEnabled?: boolean | null;
  };
  contentTeamNotifications?: {
    pushEnabled?: boolean | null;
    emailEnabled?: boolean | null;
  };
  userNotifications?: {
    pushEnabled?: boolean | null;
    emailEnabled?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Send push notifications to users by role
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-notifications".
 */
export interface PushNotification {
  id: number;
  /**
   * The title that appears in the push notification
   */
  title: string;
  /**
   * The message content (max 200 characters recommended)
   */
  body: string;
  /**
   * Select which user roles should receive this notification
   */
  targetRoles: ('admin-team' | 'content-team' | 'user')[];
  /**
   * User who created this push notification
   */
  createdBy?: (number | null) | User;
  /**
   * Status of the notification
   */
  status: 'draft' | 'sending' | 'sent' | 'failed';
  /**
   * Number of users who received this notification
   */
  recipientCount?: number | null;
  /**
   * Error message if the notification failed
   */
  error?: string | null;
  /**
   * When the notification was sent
   */
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'protocols';
        value: number | Protocol;
      } | null)
    | ({
        relationTo: 'medications';
        value: number | Medication;
      } | null)
    | ({
        relationTo: 'hospital-networks';
        value: number | HospitalNetwork;
      } | null)
    | ({
        relationTo: 'hospital-capabilities';
        value: number | HospitalCapability;
      } | null)
    | ({
        relationTo: 'hospitals';
        value: number | Hospital;
      } | null)
    | ({
        relationTo: 'hospital-change-requests';
        value: number | HospitalChangeRequest;
      } | null)
    | ({
        relationTo: 'base-change-requests';
        value: number | BaseChangeRequest;
      } | null)
    | ({
        relationTo: 'bases';
        value: number | Base;
      } | null)
    | ({
        relationTo: 'assets';
        value: number | Asset;
      } | null)
    | ({
        relationTo: 'calculators';
        value: number | Calculator;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'notification-settings';
        value: number | NotificationSetting;
      } | null)
    | ({
        relationTo: 'push-notifications';
        value: number | PushNotification;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  approved?: T;
  status?: T;
  rejectionReason?: T;
  defaultServiceLine?: T;
  pushNotificationsEnabled?: T;
  emailNotificationsEnabled?: T;
  fcmTokens?:
    | T
    | {
        token?: T;
        platform?: T;
        lastUsed?: T;
        id?: T;
      };
  notificationPreferences?:
    | T
    | {
        userRegistrations?: T;
        changeRequests?: T;
        systemNotifications?: T;
      };
  profileImage?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "protocols_select".
 */
export interface ProtocolsSelect<T extends boolean = true> {
  _order?: T;
  code?: T;
  title?: T;
  category?: T;
  subcategory?: T;
  lastModified?: T;
  sections?:
    | T
    | {
        heading?: T;
        scope?: T;
        note?: T;
        contentType?: T;
        bulletList?: T;
        richText?: T;
        actionSteps?:
          | T
          | {
              stepNumber?: T;
              action?: T;
              scope?: T;
              timing?: T;
              requiresMedControl?: T;
              protocolReferences?:
                | T
                | {
                    protocol?: T;
                    label?: T;
                    id?: T;
                  };
              details?:
                | T
                | {
                    detail?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  medications?: T;
  relatedProtocols?: T;
  keywords?: T;
  tags?: T;
  effectiveDate?: T;
  lastReviewed?: T;
  calculatorOverrides?:
    | T
    | {
        calculator?: T;
        order?: T;
        hidden?: T;
        id?: T;
      };
  attachments?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medications_select".
 */
export interface MedicationsSelect<T extends boolean = true> {
  name?: T;
  genericName?: T;
  class?: T;
  scope?: T;
  doses?:
    | T
    | {
        route?: T;
        adultDose?: T;
        pediatricDose?: T;
        concentration?: T;
        interval?: T;
        maxDose?: T;
        rate?: T;
        id?: T;
      };
  indications?: T;
  contraindications?: T;
  precautions?: T;
  mechanismOfAction?: T;
  onset?: T;
  duration?: T;
  sideEffects?: T;
  mixing?: T;
  compatibility?: T;
  titration?: T;
  specialInstructions?: T;
  pregnancyCategory?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-networks_select".
 */
export interface HospitalNetworksSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-capabilities_select".
 */
export interface HospitalCapabilitiesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  levels?:
    | T
    | {
        level?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospitals_select".
 */
export interface HospitalsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  network?: T;
  networkLogoOverride?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  coordinates?: T;
  latitude?: T;
  longitude?: T;
  squadPhone?: T;
  otherPhones?:
    | T
    | {
        label?: T;
        phoneNumber?: T;
        description?: T;
        id?: T;
      };
  doorCodes?:
    | T
    | {
        label?: T;
        code?: T;
        notes?: T;
        isPrimary?: T;
        colorTheme?: T;
        id?: T;
      };
  helipad?:
    | T
    | {
        identifier?: T;
        nightOperations?: T;
        preferredApproach?: T;
        notes?: T;
      };
  campusMaps?:
    | T
    | {
        label?: T;
        slug?: T;
        mapType?: T;
        description?: T;
        mapMedia?: T;
        externalUrl?: T;
        id?: T;
      };
  capabilities?:
    | T
    | {
        capability?: T;
        level?: T;
        id?: T;
      };
  notes?: T;
  hazards?:
    | T
    | {
        note?: T;
        id?: T;
      };
  sourceAttribution?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hospital-change-requests_select".
 */
export interface HospitalChangeRequestsSelect<T extends boolean = true> {
  type?: T;
  targetHospital?: T;
  proposedData?:
    | T
    | {
        name?: T;
        address?:
          | T
          | {
              line1?: T;
              line2?: T;
              city?: T;
              state?: T;
              zip?: T;
            };
        coordinates?: T;
        latitude?: T;
        longitude?: T;
        squadPhone?: T;
        otherPhones?:
          | T
          | {
              label?: T;
              phoneNumber?: T;
              description?: T;
              id?: T;
            };
        doorCodes?:
          | T
          | {
              label?: T;
              code?: T;
              notes?: T;
              isPrimary?: T;
              colorTheme?: T;
              id?: T;
            };
        helipad?:
          | T
          | {
              identifier?: T;
              nightOperations?: T;
              preferredApproach?: T;
              notes?: T;
            };
        campusMaps?:
          | T
          | {
              label?: T;
              slug?: T;
              mapType?: T;
              description?: T;
              mapMedia?: T;
              externalUrl?: T;
              id?: T;
            };
        capabilities?:
          | T
          | {
              capability?: T;
              level?: T;
              id?: T;
            };
        notes?: T;
        hazards?:
          | T
          | {
              note?: T;
              id?: T;
            };
        sourceAttribution?: T;
      };
  submittedBy?: T;
  status?: T;
  adminNotes?: T;
  rejectionReason?: T;
  appliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "base-change-requests_select".
 */
export interface BaseChangeRequestsSelect<T extends boolean = true> {
  type?: T;
  targetBase?: T;
  proposedData?:
    | T
    | {
        name?: T;
        address?:
          | T
          | {
              line1?: T;
              line2?: T;
              city?: T;
              state?: T;
              zip?: T;
            };
        coordinates?: T;
        latitude?: T;
        longitude?: T;
        squadPhone?: T;
        contactInfo?:
          | T
          | {
              label?: T;
              phoneNumber?: T;
              description?: T;
              id?: T;
            };
        doorCodes?:
          | T
          | {
              label?: T;
              code?: T;
              notes?: T;
              id?: T;
            };
        hazards?:
          | T
          | {
              note?: T;
              id?: T;
            };
        notes?: T;
        sourceAttribution?: T;
      };
  submittedBy?: T;
  status?: T;
  adminNotes?: T;
  rejectionReason?: T;
  appliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bases_select".
 */
export interface BasesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  network?: T;
  networkLogoOverride?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  coordinates?: T;
  latitude?: T;
  longitude?: T;
  squadPhone?: T;
  contactInfo?:
    | T
    | {
        label?: T;
        phoneNumber?: T;
        description?: T;
        id?: T;
      };
  doorCodes?:
    | T
    | {
        label?: T;
        code?: T;
        notes?: T;
        id?: T;
      };
  assets?: T;
  hazards?:
    | T
    | {
        note?: T;
        id?: T;
      };
  notes?: T;
  sourceAttribution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  emoji?: T;
  unitId?: T;
  licensePlate?: T;
  tailNumber?: T;
  capabilities?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculators_select".
 */
export interface CalculatorsSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  description?: T;
  category?: T;
  serviceLines?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  defaultOrder?: T;
  enabled?: T;
  showByDefault?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  type?: T;
  recipient?: T;
  recipientUser?: T;
  createdBy?: T;
  subject?: T;
  htmlContent?: T;
  status?: T;
  emailId?: T;
  error?: T;
  relatedUser?: T;
  relatedHospitalRequest?: T;
  relatedBaseRequest?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  action?: T;
  collection?: T;
  documentId?: T;
  changedBy?: T;
  changes?:
    | T
    | {
        field?: T;
        previousValue?: T;
        newValue?: T;
        id?: T;
      };
  metadata?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings_select".
 */
export interface NotificationSettingsSelect<T extends boolean = true> {
  notificationType?: T;
  adminNotifications?:
    | T
    | {
        pushEnabled?: T;
        emailEnabled?: T;
      };
  contentTeamNotifications?:
    | T
    | {
        pushEnabled?: T;
        emailEnabled?: T;
      };
  userNotifications?:
    | T
    | {
        pushEnabled?: T;
        emailEnabled?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-notifications_select".
 */
export interface PushNotificationsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  targetRoles?: T;
  createdBy?: T;
  status?: T;
  recipientCount?: T;
  error?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site header configuration (admin only)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Header logo (recommended: SVG or PNG with transparent background)
   */
  logo?: (number | null) | Media;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site footer configuration (admin only)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide settings and configuration (admin only)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The name of your organization
   */
  siteName: string;
  /**
   * Site logo displayed in header (recommended: SVG or PNG with transparent background)
   */
  logo?: (number | null) | Media;
  /**
   * Browser tab icon (recommended: 32x32 PNG or ICO)
   */
  favicon?: (number | null) | Media;
  /**
   * Optional background image for the hero section
   */
  heroBackgroundImage?: (number | null) | Media;
  /**
   * Small badge text above the main headline
   */
  heroBadgeText?: string | null;
  /**
   * Main headline on the homepage
   */
  heroTitle: string;
  /**
   * Word or phrase to highlight in red (must appear in hero title)
   */
  heroHighlight?: string | null;
  /**
   * Subtitle text below the headline
   */
  heroSubtitle: string;
  heroPrimaryButtonText?: string | null;
  heroPrimaryButtonLink?: string | null;
  heroSecondaryButtonText?: string | null;
  /**
   * Optional link for secondary button
   */
  heroSecondaryButtonLink?: string | null;
  /**
   * Opacity at the top of the gradient overlay (0-100)
   */
  heroGradientTopOpacity?: number | null;
  /**
   * Opacity at the middle of the gradient overlay (0-100)
   */
  heroGradientMidOpacity?: number | null;
  /**
   * Opacity at the bottom of the gradient overlay (0-100)
   */
  heroGradientBottomOpacity?: number | null;
  /**
   * Base color for the gradient overlay
   */
  heroGradientColor?: ('black' | 'navy' | 'darkblue' | 'darkgray') | null;
  stats?:
    | {
        number: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  featuresTitle?: string | null;
  featuresSubtitle?: string | null;
  ctaTitle?: string | null;
  ctaSubtitle?: string | null;
  ctaPrimaryButtonText?: string | null;
  ctaSecondaryButtonText?: string | null;
  /**
   * General contact email address
   */
  contactEmail?: string | null;
  /**
   * Contact phone number
   */
  contactPhone?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'github';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Default title for pages without a specific meta title and the base value used for social shares
   */
  metaTitle?: string | null;
  /**
   * Site or organization name shown on social share cards
   */
  metaSiteName?: string | null;
  /**
   * Default description for search engines (160 characters max)
   */
  metaDescription?: string | null;
  /**
   * Default image for social media shares (recommended: 1200x630px)
   */
  metaImage?: (number | null) | Media;
  /**
   * Optional Twitter/X handle (with @) used on summary cards
   */
  metaTwitterHandle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  heroBackgroundImage?: T;
  heroBadgeText?: T;
  heroTitle?: T;
  heroHighlight?: T;
  heroSubtitle?: T;
  heroPrimaryButtonText?: T;
  heroPrimaryButtonLink?: T;
  heroSecondaryButtonText?: T;
  heroSecondaryButtonLink?: T;
  heroGradientTopOpacity?: T;
  heroGradientMidOpacity?: T;
  heroGradientBottomOpacity?: T;
  heroGradientColor?: T;
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  featuresTitle?: T;
  featuresSubtitle?: T;
  ctaTitle?: T;
  ctaSubtitle?: T;
  ctaPrimaryButtonText?: T;
  ctaSecondaryButtonText?: T;
  contactEmail?: T;
  contactPhone?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  metaTitle?: T;
  metaSiteName?: T;
  metaDescription?: T;
  metaImage?: T;
  metaTwitterHandle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}